plugin_path="out"
extra_plugins=[
  "babel.so",
  "node_compat.so",
  "squircy2_compat.so",
  "script.so",
]

[irc]
nick="squishyjones"
user="mrjones"
network="chat.freenode.net:6697"
tls=true
sasl=false
#sasl_username=""
#sasl_password=""
#server_password=""

[vm]
modules_path="node_modules"

[babel]
enable=true

[script]
scripts_path="scripts"

[squircy2_compat]
enable_file_api=false
file_api_root="files"
#owner_nick=""
#owner_host=""
data_path="data"

[node_compat]
enable_exec=false
